# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Card": "00_core.ipynb",
         "Deck": "00_core.ipynb",
         "Hand": "00_core.ipynb",
         "find_defining_class": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://ogr003.github.io/mapaccounting2/"

git_url = "https://github.com/ogr003/mapaccounting2/tree/master/"

def custom_doc_links(name): return None
